Skip to content
ManasKumarJena
/
node-task

Type / to search

Code
Issues
Pull requests
Actions
Projects
Wiki
Security
Insights
Settings
CI/CD Pipeline
Update main.yml #18
Jobs
Run details
Workflow file for this run
.github/workflows/main.yml at 4e22546
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest

    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP_NAME: your-heroku-app-name
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Log in to Docker Hub
        run: echo "${DOCKERHUB_TOKEN}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin

      - name: Pull Docker image from Docker Hub
        run: docker pull heroku/heroku
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Heroku CLI
        uses: docker://ghcr.io/actions/heroku
        with:
          heroku-api-key: ${{ secrets.HEROKU_API_KEY }}

      - name: Deploy to Heroku
        run: |
          echo "Deploying to Heroku..."
          git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:refs/heads/main
Update main.yml · ManasKumarJena/node-task@4e22546 
