name: Node.js CI/CD

on:
  push:
    branches:
      - main  # Adjust this to match your main branch name

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}  # Define your Heroku API key as a secret in your repository settings

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm test

  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    needs: test  # Ensure the test job completes successfully before deploying

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Heroku CLI
      uses: actions/heroku@v2
      with:
        heroku-api-key: ${{ env.HEROKU_API_KEY }}

    - name: Login to Heroku
      run: heroku container:login

    - name: Build and Push Docker Image
      run: |
        docker build -t registry.heroku.com/demo-app/web .
        docker push registry.heroku.com/demo-app/web

    - name: Release to Heroku
      run: heroku container:release -a demo-app web
