name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest

    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP_NAME: your-heroku-app-name

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Heroku CLI v3
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          sudo ln -s /usr/local/heroku/bin/heroku /usr/local/bin/heroku
          
      - name: Verify Heroku CLI installation
        run: heroku --version

      - name: Deploy to Heroku
        run: |
          echo "Deploying to Heroku..."
          git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:refs/heads/main
